# apps/kustomization.yaml
# This file includes all your application *categories*.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # We will add networking, monitoring, etc. here
  - networking
