# This is the main file that installs the chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring # Deploy the app into its new namespace
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.0.3" # Pinning the version is good practice
      sourceRef:
        kind: HelmRepository
        name: prometheus-community # Matches the name in helm-repo.yaml
      interval: 15m
  values:
    # Set the admin password for your Grafana dashboard
    grafana:
      adminPassword: "admin123" # !!! CHANGE THIS !!!

    # We need to give Prometheus storage
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi # 10GB is a good start for metrics
